In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('dataset.csv')
df

,age,body_temperature,chronic_disease,breathing_issue,Blood O2 Level in Percentage,Needed Hospitalization
0,10.0,Normal,no,no,97.0,No
1,12.0,Normal,no,no,97.0,No
2,15.0,Normal,no,no,94.0,No
3,10.0,Normal,no,no,97.0,No
4,13.0,Moderate,no,no,94.0,No
...,...,...,...,...,...,...
65,86.0,High,no,yes,76.0,Yes
66,61.0,Moderate,no,yes,90.0,No
67,94.0,High,yes,yes,64.0,Yes
68,81.0,High,yes,yes,75.0,Yes
69,76.0,High,yes,yes,80.0,Yes

In [3]:
df.dropna(axis=0,inplace=True)

In [4]:
df

,age,body_temperature,chronic_disease,breathing_issue,Blood O2 Level in Percentage,Needed Hospitalization
0,10.0,Normal,no,no,97.0,No
1,12.0,Normal,no,no,97.0,No
2,15.0,Normal,no,no,94.0,No
3,10.0,Normal,no,no,97.0,No
4,13.0,Moderate,no,no,94.0,No
...,...,...,...,...,...,...
65,86.0,High,no,yes,76.0,Yes
66,61.0,Moderate,no,yes,90.0,No
67,94.0,High,yes,yes,64.0,Yes
68,81.0,High,yes,yes,75.0,Yes
69,76.0,High,yes,yes,80.0,Yes

In [5]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
lb=LabelEncoder()
l=list(df.columns)
l.remove('Blood O2 Level in Percentage')
l.remove('age')
for i in l:
    df[i]=lb.fit_transform(df[i])

In [6]:
df

,age,body_temperature,chronic_disease,breathing_issue,Blood O2 Level in Percentage,Needed Hospitalization
0,10.0,2,0,0,97.0,0
1,12.0,2,0,0,97.0,0
2,15.0,2,0,0,94.0,0
3,10.0,2,0,0,97.0,0
4,13.0,1,0,0,94.0,0
...,...,...,...,...,...,...
65,86.0,0,0,1,76.0,1
66,61.0,1,0,1,90.0,0
67,94.0,0,1,1,64.0,1
68,81.0,0,1,1,75.0,1
69,76.0,0,1,1,80.0,1

In [9]:
X=df.drop(columns=['Needed Hospitalization'],axis=1)
y=df['Needed Hospitalization']

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',random_state=42)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0